[tool.black]
line-length = 100

[tool.poetry]
name = "vtasks"
version = "1.0.0"
description = "Personal tasks scheduled with Luigi"
authors = ["Arnau Villoro <arnau@villoro.com>"]
maintainers = ["Arnau Villoro <arnau@villoro.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/villoro/vtasks"

[tool.poetry.dependencies]
python = "^3.7.9"
cryptocompare = "^0.7.3"
dropbox = "^11.0.0"
gcsa = "^1.2.0"
gspread = "^3.6.0"
jinja2 = "^2.11.2"
loguru = "^0.5.3"
numpy = "^1.18.4"
openpyxl = "^3.0.3"
oyaml = "^1.0"
pandas = "^1.0.3"
prefect = "^0.13.9"
pyarrow = "^2.0.0"
pykrakenapi = "^0.1.9"
regex = "^2020.10.28"
vcrypto = "^2.1.0"
vdropbox = "^0.2.7"
vpalette = "^2.0.0"
vtime = "^2.0.0"
xlrd = "^1.2.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
jupyter = "^1.0.0"
notebook = "^6.0.3"
pre-commit = "^2.3.0"
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
